User.create(name: "Admin", admin: true, status: "active", email: "admin@gmail.com", password: 123456, password_confirmation: 123456)
User.create(name: "User", admin: false, status: "notactive", email: "user@gmail.com", password: 123456, password_confirmation: 123456)
User.create(name: "User_2", admin: false, status: "active", email: "user2@gmail.com", password: 123456, password_confirmation: 123456)
User.create(name: "User_3", admin: false, status: "notactive", email: "user3@gmail.com", password: 123456, password_confirmation: 123456)
User.create(name: "User_4", admin: false, status: "denied", email: "user4@gmail.com", password: 123456, password_confirmation: 123456)